
#ifndef QPLAYER_CONSTANTS_H
#define QPLAYER_CONSTANTS_H


#define THREAD_MAIN 1
#define THREAD_CHILD 2

#define ERROR_FFMPEG_CAN_NOT_OPEN_URL 3
#define ERROR_FFMPEG_CAN_NOT_FIND_STREAMS 4

#define CODEC_TYPE_OTHER  -1
#define CODEC_TYPE_H264  1
#define CODEC_TYPE_HEVC  2
#define CODEC_TYPE_MPEG4  3
#define CODEC_TYPE_WMV  4

#define DECODE_SOFTWARE  0
#define DECODE_HARDWARE  1

#endif //QPLAYER_CONSTANTS_H

